### ISSUE TITLE
How to deploy it to Heroku?

### ISSUE THREAD

**Issue by alexbagirov** [shaunburdick/slack-ooo#10]

**Comment by shaunburdick** [comment]
I haven't really looked into Heroku that much, but based on the [documentation](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction)
It appears you could:
- fork this repo
- clone it down to your computer
- define a [procfile](https://devcenter.heroku.com/articles/procfile) with something along the lines of `web: npm start`
- define a `.env` file with your slack info in it or do a `heroku config:set SLACK_TOKEN=your-token`

You don't really need to worry about copying the `config.js` as you can define your config in the environment variables.

**Comment by alexbagirov** [comment]
Ok, so if I'm not going to use Heroku then how can I deploy it to VPS on Ubuntu?

**Comment by shaunburdick** [comment]
Welp, you can checkout the install section on the [README.md](https://github.com/shaunburdick/slack-ooo#install)
If you are using Ubuntu 14.04, you can [install docker](https://docs.docker.com/installation/ubuntulinux/) and run it inside that via

```
docker run -it \
-e SLACK_TOKEN=xobo-blarty-blar-blar \
shaunburdick/slack-ooo:latest
```
