### ISSUE TITLE
running slack-ooo in a docker container in detached mode

### ISSUE THREAD

**Issue by sampritavh** [shaunburdick/slack-ooo#11]
I am running the slack-ooo using the officialk docker image in a detached mode. Here is the command I used: 
`docker run -d -e SLACK_TOKEN=xoxb-my-token> -e SLACK_AUTO_RECONNECT=true -e SLACK_AUTO_MARK=true shaunburdick/slack-ooo:latest --name ooo_bot`
It runs fine for few hours. But after that it stops responding although it shows online in Slack. When I looked in to the docker container logs, I can see that it has actually responded but for some reason the message is not showing up in slack. I am not sure if it is a bug or if I am missing any other settings.  Would really appreciate if I can get any help in this regard.

**Comment by shaunburdick** [comment]
Hmmm, let me look into the slack library to see if it returns some sort of response for a failed send.
I should work on #1 too so that we don't lose our statuses on restart.
